spring:
  profiles:
    active:
      - sandbox
    group:
      prod:
        - prod
        - urls
      sandbox:
        - sandbox
        - urls

logging:
  level:
    root: INFO
    kr:
      co:
        nicepay:
          untact:
            core:
              interceptor: DEBUG