# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'untact-test-sample/'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'untact-test-sample/'

permissions:
  contents: read

defaults:
  run:
    working-directory: untact-test-sample

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 레포지토리 체크아웃
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # 한국시간 설정
      - name: TimeZone을 Asia/Seoul로 설정합니다
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      # 2) JDK 11 버전 설치,
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # gradle 실행 권한 부여
      - name: Gradle 명령 실행을 위한 권한을 부여합니다
        run: chmod +x gradlew

      # gradle test
      - name: Test with Gradle
        run: ./gradlew -Dspring.profiles.active=test -d test

      # 테스트 후 PR comment 등록
      - name: 테스트 결과를 PR에 코멘트로 등록합니다
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      # 테스트 후 check comment 등록
      - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트를 등록합니다
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      # 프로젝트 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test